import localFont from "next/font/local";
import "./globals.css";
import DarkModeWrapper from "../components/dark-mode-wrapper";
import { Analytics } from "@vercel/analytics/react"

const geistSans = localFont({
  src: "fonts/ABCFavoritMono-Light.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "fonts/ABCFavoritMono-Light.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Jhon Boy Development",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <DarkModeWrapper>{children}</DarkModeWrapper>
      </body>
      <Analytics/>
    </html>
  );
}
